# Generated by Django 2.0.5 on 2018-05-09 08:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(default=uuid.UUID('f24204c4-a8c8-4c94-957a-9debfd3b37bb'), max_length=36, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('send_time', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(default='未读', max_length=10)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageReceiverId', to='user.User')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageSenderId', to='user.User')),
            ],
        ),
    ]
