# Generated by Django 2.0.5 on 2018-05-09 12:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.CharField(default=uuid.UUID('c10b5a55-ae88-4153-9ec3-299ee9217b64'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='state',
            field=models.CharField(default='未读', max_length=10, null=True),
        ),
    ]
