# Generated by Django 2.0.5 on 2018-05-09 12:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20180509_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.CharField(default=uuid.UUID('06a9d8ce-a9b3-4fa2-9d6f-2b4e8d877df6'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
