# Generated by Django 2.0.5 on 2018-05-09 08:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.CharField(default=uuid.UUID('a0c38eb9-e036-4f84-aaa5-37ef8220d4bf'), max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('type', models.CharField(max_length=10)),
                ('state', models.CharField(default='未共享', max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('release_time', models.DateTimeField(auto_now_add=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goodBorrowerId', to='user.User')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goodOwnerId', to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, unique=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictureGoodId', to='good.Good')),
            ],
        ),
        migrations.CreateModel(
            name='ShareRequest',
            fields=[
                ('id', models.CharField(default=uuid.UUID('2d5fe539-f46c-4439-af5a-b9dd05a73584'), max_length=36, primary_key=True, serialize=False)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(default='未处理', max_length=10)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestGoodId', to='good.Good')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestOwnerId', to='user.User')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesterId', to='user.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='picture',
            unique_together={('url', 'good')},
        ),
    ]
