# Generated by Django 2.0.5 on 2018-05-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0002_auto_20180509_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='state',
            field=models.CharField(default='未共享', max_length=10, null=True),
        ),
    ]
