# Generated by Django 2.0.5 on 2018-05-09 08:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=uuid.UUID('21183fdc-538c-4afe-967c-047c1572a888'), max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('sex', models.CharField(max_length=1)),
                ('url', models.CharField(default='/resources/DefaultUserHeadPicture.png', max_length=512)),
            ],
        ),
    ]
